#!/bin/sh

## WARNING!!! FOR LOCAL DEVELOPMENT OF THE DOCKERFILE ONLY!!! ANY OTHER DEV USE SHOULD BE HANDLED EITHER BY THE TYPICAL "npm run dev" OR SOME STANDARDIZED METHODS FOR A GIVEN DEV-AGENT (eg. Lovable), WHATEVER THOSE METHODS MAY BE. ANY PRODUCTION DOCKER DEPLOYMENT SHOULD BE HANDLED BY MORE SENSIBLE DOCKER DEPLOYMENT AND BUILD SYSTEMS, EG. COMPOSE OR JIFOCC. ##

docker build -t ghostland-gate .
docker run --rm --network host ghostland-gate
docker rmi ghostland-gate